Update build-push.yml
Capture error code

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -21,7 +21,12 @@ jobs:
         id: tag
         working-directory: llama.cpp
         run: |
-          tag=$(git describe --tags --abbrev=0) || exit 1
+          tag=$(git describe --tags --abbrev=0)
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Failed to retrieve tag."
+            exit $exit_code
+          fi
           echo "build_number=$tag" >> $GITHUB_OUTPUT
 
       - name: Checkout my repository
